/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account. Duplicate email → 409, weak password → 422.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Sign in with email + password. Invalid credentials → generic 401.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Read the current user's profile.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Update the current user's display name.
         */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Sign out: clear the presenting client's cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List History: every Session record, newest first, optionally filtered by
         *     phase(s).
         *
         *     Requires a sign-in cookie (#145). Records are not scoped per User yet: every
         *     signed-in caller is shown the same list (see
         *     ``tests/routers/test_auth_gate.TestSessionsSharedAcrossUsers``).
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a session and make the first Clarify graph call.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get current session state & progress.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Explore Sessions
         * @description List the public Explore feed: Sessions that reached materials.
         *
         *     Newest first, capped at ``EXPLORE_LIMIT``. Reuses the ``SessionList`` /
         *     ``SessionListItem`` schema from ``/sessions`` and carries no owner
         *     identity — no email, display name, or user id — so a Visitor sees what
         *     people are learning without being told who they are.
         */
        get: operations["list_explore_sessions_explore_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clarify Session
         * @description Resume the Clarify graph loop with the learner's answer.
         */
        post: operations["clarify_session_sessions__session_id__clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Session
         * @description Start the probe or submit the answers for the current batch (combined endpoint).
         */
        post: operations["probe_session_sessions__session_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Plan
         * @description Trigger plan generation.
         */
        post: operations["generate_plan_sessions__session_id__plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust Plan
         * @description Submit a free-text adjustment and get the regenerated plan.
         */
        post: operations["adjust_plan_sessions__session_id__plan_adjust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Approve the plan, then start material generation in the background.
         */
        post: operations["approve_plan_sessions__session_id__plan_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/sessions/{session_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Regenerate
         * @description Dev-only: wipe existing materials and re-run generation.
         *
         *     Requires the session to already have a plan and boundary_map
         *     (i.e. it has passed the planning phase). Skips all upstream phases.
         */
        post: operations["dev_regenerate_dev_sessions__session_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Materials
         * @description Poll material generation progress with full content.
         */
        get: operations["get_materials_sessions__session_id__materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slides/{slide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slide
         * @description Fetch raw slide JSX (component source) by globally-unique slide ID (internal).
         */
        get: operations["get_slide_slides__slide_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Card
         * @description Capture a missed question (material misses from the client; probe
         *     misses are recorded server-side). Re-miss resets the card's SRS.
         */
        post: operations["record_card_review_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Due Cards
         * @description The learner's due cards ordered by ``due_at``.
         */
        get: operations["due_cards_review_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/cards/{card_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Card
         * @description Submit a confidence rating: update the card's FSRS state and return
         *     the new due date, derived interval, and lapse count.
         */
        post: operations["answer_card_review_cards__card_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustIn */
        AdjustIn: {
            /** Adjustment */
            adjustment: string;
        };
        /** AnswerIn */
        AnswerIn: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Selected Index */
            selected_index: number;
        };
        /** ApproveOut */
        ApproveOut: {
            phase: components["schemas"]["Phase"];
            /** Message */
            message: string;
        };
        /** ClarifyIn */
        ClarifyIn: {
            /** Answer */
            answer: string;
        };
        /**
         * ClarifyResult
         * @description Outcome of a Clarify graph call: either questions or a narrowed goal.
         */
        ClarifyResult: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Narrowed Goal */
            narrowed_goal?: string | null;
            /** Clarifying Questions */
            clarifying_questions?: string[] | null;
        };
        /** GoalIn */
        GoalIn: {
            /** Goal */
            goal: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MaterialOut */
        MaterialOut: {
            /** Step Id */
            step_id: string;
            summary: components["schemas"]["SummaryOut"];
            /** Items */
            items: (components["schemas"]["SlideItem"] | components["schemas"]["QuestionItem"])[];
        };
        /** MaterialsOut */
        MaterialsOut: {
            phase: components["schemas"]["Phase"];
            /** Generated Steps */
            generated_steps: components["schemas"]["MaterialOut"][];
        };
        /** Message */
        Message: {
            /** Message */
            message: string;
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "clarifying" | "probing" | "planning" | "reviewing" | "generating" | "executing" | "complete" | "error";
        /** PlanBody */
        PlanBody: {
            /** Prose Summary */
            prose_summary: string;
            /** Dependency Dag */
            dependency_dag: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** PlanOut */
        PlanOut: {
            phase: components["schemas"]["Phase"];
            plan: components["schemas"]["PlanBody"];
        };
        /** ProbeIn */
        ProbeIn: {
            /** Answers */
            answers?: components["schemas"]["AnswerIn"][] | null;
        };
        /** ProbeOut */
        ProbeOut: {
            phase: components["schemas"]["Phase"];
            /** Questions */
            questions?: components["schemas"]["ProbeQuestionOut"][] | null;
            /** Boundary Map */
            boundary_map?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
        };
        /** ProbeQuestionOut */
        ProbeQuestionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
            /** Strand */
            strand: string;
            /** Difficulty */
            difficulty: number;
        };
        /** Progress */
        Progress: {
            /** Current Step Id */
            current_step_id: string | null;
            /** Completed Steps */
            completed_steps: string[];
            /** Total Steps */
            total_steps: number;
            /** Step Scores */
            step_scores: {
                [key: string]: number;
            };
        };
        /** QuestionItem */
        QuestionItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "question";
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** ReviewAnswerIn */
        ReviewAnswerIn: {
            /**
             * Rating
             * @enum {string}
             */
            rating: "again" | "hard" | "good" | "easy";
        };
        /** ReviewAnswerOut */
        ReviewAnswerOut: {
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Interval Days */
            interval_days: number;
            /** Lapses */
            lapses: number;
        };
        /** ReviewCardIn */
        ReviewCardIn: {
            /** Source */
            source: string;
            /** Session Id */
            session_id: string;
            /** Question Id */
            question_id: string;
            question: components["schemas"]["ReviewQuestionIn"];
            /** Step Id */
            step_id?: string | null;
            /** Selected Index */
            selected_index?: number | null;
        };
        /** ReviewCardOut */
        ReviewCardOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            question: components["schemas"]["ReviewQuestionOut"];
            /** Session Id */
            session_id: string;
            /** Step Id */
            step_id?: string | null;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Lapses */
            lapses: number;
        };
        /** ReviewQuestionIn */
        ReviewQuestionIn: {
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
        };
        /** ReviewQuestionOut */
        ReviewQuestionOut: {
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
        };
        /** SessionList */
        SessionList: {
            /** Sessions */
            sessions: components["schemas"]["SessionListItem"][];
        };
        /** SessionListItem */
        SessionListItem: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Goal */
            goal: string;
            /** Narrowed Goal */
            narrowed_goal: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Narrowed Goal */
            narrowed_goal: string | null;
            progress: components["schemas"]["Progress"];
        };
        /** SlideItem */
        SlideItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "slide";
            /** Slide Id */
            slide_id: string;
        };
        /** SlideOut */
        SlideOut: {
            /** Slide Id */
            slide_id: string;
            /** Content */
            content: string;
        };
        /** StepOut */
        StepOut: {
            /** Id */
            id: string;
            /**
             * Letter
             * @default
             */
            letter: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Depends On */
            depends_on: string[];
            /** Depth */
            depth: number;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Step Id */
            step_id: string;
            /** Title */
            title: string;
            /** Key Points */
            key_points: string[];
        };
        /** UpdateMeRequest */
        UpdateMeRequest: {
            /** Display Name */
            display_name: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                phase?: components["schemas"]["Phase"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_explore_sessions_explore_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
        };
    };
    clarify_session_sessions__session_id__clarify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_session_sessions__session_id__probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_sessions__session_id__plan_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_plan_sessions__session_id__plan_adjust_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_sessions__session_id__plan_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dev_regenerate_dev_sessions__session_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_materials_sessions__session_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slide_slides__slide_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_card_review_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCardIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    due_cards_review_due_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_card_review_cards__card_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
