/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List all sessions, newest first, optionally filtered by phase(s).
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a session and make the first Clarify graph call.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get current session state & progress.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clarify Session
         * @description Resume the Clarify graph loop with the learner's answer.
         */
        post: operations["clarify_session_sessions__session_id__clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Session
         * @description Start the probe or submit the answers for the current batch (combined endpoint).
         */
        post: operations["probe_session_sessions__session_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Plan
         * @description Trigger plan generation.
         */
        post: operations["generate_plan_sessions__session_id__plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust Plan
         * @description Submit a free-text adjustment and get the regenerated plan.
         */
        post: operations["adjust_plan_sessions__session_id__plan_adjust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Approve the plan, then start material generation in the background.
         */
        post: operations["approve_plan_sessions__session_id__plan_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/sessions/{session_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Regenerate
         * @description Dev-only: wipe existing materials and re-run generation.
         *
         *     Requires the session to already have a plan and boundary_map
         *     (i.e. it has passed the planning phase). Skips all upstream phases.
         */
        post: operations["dev_regenerate_dev_sessions__session_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Materials
         * @description Poll material generation progress with full content.
         */
        get: operations["get_materials_sessions__session_id__materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slides/{slide_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slide
         * @description Fetch raw slide JSX (component source) by globally-unique slide ID (internal).
         */
        get: operations["get_slide_slides__slide_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustIn */
        AdjustIn: {
            /** Adjustment */
            adjustment: string;
        };
        /** AnswerIn */
        AnswerIn: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Selected Index */
            selected_index: number;
        };
        /** ApproveOut */
        ApproveOut: {
            phase: components["schemas"]["Phase"];
            /** Message */
            message: string;
        };
        /** ClarifyIn */
        ClarifyIn: {
            /** Answer */
            answer: string;
        };
        /**
         * ClarifyResult
         * @description Outcome of a Clarify graph call: either questions or a narrowed goal.
         */
        ClarifyResult: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Narrowed Goal */
            narrowed_goal?: string | null;
            /** Clarifying Questions */
            clarifying_questions?: string[] | null;
        };
        /** GoalIn */
        GoalIn: {
            /** Goal */
            goal: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialOut */
        MaterialOut: {
            /** Step Id */
            step_id: string;
            summary: components["schemas"]["SummaryOut"];
            /** Items */
            items: (components["schemas"]["SlideItem"] | components["schemas"]["QuestionItem"])[];
        };
        /** MaterialsOut */
        MaterialsOut: {
            phase: components["schemas"]["Phase"];
            /** Generated Steps */
            generated_steps: components["schemas"]["MaterialOut"][];
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "clarifying" | "probing" | "planning" | "reviewing" | "generating" | "executing" | "complete" | "error";
        /** PlanBody */
        PlanBody: {
            /** Prose Summary */
            prose_summary: string;
            /** Dependency Dag */
            dependency_dag: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** PlanOut */
        PlanOut: {
            phase: components["schemas"]["Phase"];
            plan: components["schemas"]["PlanBody"];
        };
        /** ProbeIn */
        ProbeIn: {
            /** Answers */
            answers?: components["schemas"]["AnswerIn"][] | null;
        };
        /** ProbeOut */
        ProbeOut: {
            phase: components["schemas"]["Phase"];
            /** Questions */
            questions?: components["schemas"]["ProbeQuestionOut"][] | null;
            /** Boundary Map */
            boundary_map?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
        };
        /** ProbeQuestionOut */
        ProbeQuestionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
            /** Strand */
            strand: string;
            /** Difficulty */
            difficulty: number;
        };
        /** Progress */
        Progress: {
            /** Current Step Id */
            current_step_id: string | null;
            /** Completed Steps */
            completed_steps: string[];
            /** Total Steps */
            total_steps: number;
            /** Step Scores */
            step_scores: {
                [key: string]: number;
            };
        };
        /** QuestionItem */
        QuestionItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "question";
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
        };
        /** SessionList */
        SessionList: {
            /** Sessions */
            sessions: components["schemas"]["SessionListItem"][];
        };
        /** SessionListItem */
        SessionListItem: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Goal */
            goal: string;
            /** Narrowed Goal */
            narrowed_goal: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Narrowed Goal */
            narrowed_goal: string | null;
            progress: components["schemas"]["Progress"];
        };
        /** SlideItem */
        SlideItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "slide";
            /** Slide Id */
            slide_id: string;
        };
        /** SlideOut */
        SlideOut: {
            /** Slide Id */
            slide_id: string;
            /** Content */
            content: string;
        };
        /** StepOut */
        StepOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Depends On */
            depends_on: string[];
            /** Depth */
            depth: number;
        };
        /** SummaryOut */
        SummaryOut: {
            /** Step Id */
            step_id: string;
            /** Title */
            title: string;
            /** Key Points */
            key_points: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                phase?: components["schemas"]["Phase"][] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clarify_session_sessions__session_id__clarify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_session_sessions__session_id__probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_sessions__session_id__plan_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_plan_sessions__session_id__plan_adjust_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_sessions__session_id__plan_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dev_regenerate_dev_sessions__session_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_materials_sessions__session_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slide_slides__slide_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
