/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Create a session and make the first Clarify graph call.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clarify Session
         * @description Resume the Clarify graph loop with the learner's answer.
         */
        post: operations["clarify_session_sessions__session_id__clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Get current session state & progress.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Session
         * @description Start the probe or submit the next answer (combined endpoint).
         */
        post: operations["probe_session_sessions__session_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Plan
         * @description Trigger plan generation.
         */
        post: operations["generate_plan_sessions__session_id__plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adjust Plan
         * @description Submit a free-text adjustment and get the regenerated plan.
         */
        post: operations["adjust_plan_sessions__session_id__plan_adjust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Plan
         * @description Approve the plan and transition to generating.
         */
        post: operations["approve_plan_sessions__session_id__plan_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Materials
         * @description Poll material generation progress with full content.
         */
        get: operations["get_materials_sessions__session_id__materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustIn */
        AdjustIn: {
            /** Adjustment */
            adjustment: string;
        };
        /** ApproveOut */
        ApproveOut: {
            phase: components["schemas"]["Phase"];
            /** Message */
            message: string;
        };
        /** ClarifyIn */
        ClarifyIn: {
            /** Answer */
            answer: string;
        };
        /**
         * ClarifyResult
         * @description Outcome of a Clarify graph call: either questions or a narrowed goal.
         */
        ClarifyResult: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Narrowed Goal */
            narrowed_goal?: string | null;
            /** Clarifying Questions */
            clarifying_questions?: string[] | null;
        };
        /** GoalIn */
        GoalIn: {
            /** Goal */
            goal: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialOut */
        MaterialOut: {
            /** Step Id */
            step_id: string;
            /** Slides */
            slides: string[];
            /** Questions */
            questions: components["schemas"]["QuestionOut"][];
        };
        /** MaterialsOut */
        MaterialsOut: {
            phase: components["schemas"]["Phase"];
            /** Generated Steps */
            generated_steps: components["schemas"]["MaterialOut"][];
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "clarifying" | "probing" | "planning" | "reviewing" | "generating" | "executing" | "complete";
        /** PlanBody */
        PlanBody: {
            /** Prose Summary */
            prose_summary: string;
            /** Dependency Dag */
            dependency_dag: string;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** PlanOut */
        PlanOut: {
            phase: components["schemas"]["Phase"];
            plan: components["schemas"]["PlanBody"];
        };
        /** ProbeIn */
        ProbeIn: {
            /** Question Id */
            question_id?: string | null;
            /** Selected Index */
            selected_index?: number | null;
        };
        /** ProbeOut */
        ProbeOut: {
            phase: components["schemas"]["Phase"];
            question?: components["schemas"]["ProbeQuestionOut"] | null;
            /** Boundary Map */
            boundary_map?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
        };
        /** ProbeQuestionOut */
        ProbeQuestionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
            /** Strand */
            strand: string;
            /** Difficulty */
            difficulty: number;
        };
        /** Progress */
        Progress: {
            /** Current Step Id */
            current_step_id: string | null;
            /** Completed Steps */
            completed_steps: string[];
            /** Total Steps */
            total_steps: number;
            /** Step Scores */
            step_scores: {
                [key: string]: number;
            };
        };
        /** QuestionOut */
        QuestionOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Options */
            options: string[];
            /** Correct Index */
            correct_index: number;
            /** Explanation */
            explanation: string;
        };
        /** SessionState */
        SessionState: {
            /** Session Id */
            session_id: string;
            phase: components["schemas"]["Phase"];
            /** Narrowed Goal */
            narrowed_goal: string | null;
            progress: components["schemas"]["Progress"];
        };
        /** StepOut */
        StepOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Depends On */
            depends_on: string[];
            /** Depth */
            depth: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clarify_session_sessions__session_id__clarify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_session_sessions__session_id__probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_sessions__session_id__plan_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_plan_sessions__session_id__plan_adjust_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_plan_sessions__session_id__plan_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_materials_sessions__session_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
