// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "app": {
    "title": "Learn Anything",
    "description": "An AI conversation-driven learning assistant: declare a knowledge point and it walks you to mastery, one question at a time."
  },
  "topbar": {
    "chooseLanguage": "Choose language",
    "toggleTheme": "Toggle theme",
    "reviewDue": "{count} cards due for review",
    "study": "Study",
    "review": "Review"
  },
  "account": {
    "displayName": "Display name",
    "editName": "Edit display name",
    "signOut": "Sign out",
    "save": "Save",
    "namePlaceholder": "Your name",
    "error": "Something went wrong. Please try again."
  },
  "home": {
    "title": "My Sessions",
    "subtitle": "Resume your deep dives or launch a new contextual inquiry.",
    "emptyTitle": "No sessions yet",
    "emptyBody": "Start your first deep dive or launch a contextual inquiry to begin your learning journey.",
    "startNewSession": "Start New Session",
    "generating": "Generating materials…",
    "loading": {
      "title": "Loading your sessions…",
      "note": "Hang tight — your history is loading."
    },
    "error": {
      "title": "Can't load your sessions",
      "note": "We couldn't reach the backend. Your sessions are safe — try again."
    },
    "retry": "Retry"
  },
  "dialog": {
    "openingPrompt": "Tell us what you'd like to explore or learn, and we'll shape a session around it.",
    "title": "Start New Session",
    "close": "Close",
    "recentMessages": "Recent Messages",
    "messages": "{n, plural, one {# message} other {# messages}}",
    "you": "You",
    "lumina": "Lumina AI",
    "labelClarify": "What would you like to explore or learn?",
    "labelProbe": "Which option is right?",
    "labelReview": "How should we adjust the plan?",
    "placeholderReview": "Type 'approve' to approve, or describe how to adjust — press Enter to send",
    "placeholderDefault": "Continue the discussion or describe the next query...",
    "pendingPlan": "We're drafting your learning plan. This takes a few seconds — hang tight.",
    "pendingReview": "We're updating your plan to match your feedback. This takes a few seconds.",
    "pendingProbeAnswer": "We're checking your answer. Give it a moment.",
    "pendingProbeGenerate": "We're generating questions to check your current level of mastery. Give it a moment.",
    "pendingClarify": "We're working through what you shared. Give it a moment.",
    "pendingDefault": "We're working out what you want to learn. Give it a moment.",
    "confirm": "Confirm",
    "cancel": "Cancel",
    "send": "Send",
    "sending": "Sending…",
    "errorFallback": "Something went wrong starting your session. Please try again.",
    "yourNarrowedGoal": "Your narrowed goal is: {goal}",
    "boundaryEstablished": "Boundary established after {n, plural, one {# question} other {# questions}}. Your learning plan is ready.",
    "thinFeedback": "That's a bit thin — add a little more detail.",
    "errorNoQuestions": "No questions were received — please try again.",
    "errorApproveHint": "Type 'approve' to approve the plan, or describe how to adjust it.",
    "errorSession": "Something went wrong with your session. Please try again.",
    "errorApprovePlan": "Something went wrong approving your plan. Please try again.",
    "railStep0": "Clarifying",
    "railStep1": "Probing",
    "railStep2": "Planning",
    "railStep3": "Generating",
    "railCounterReady": "3 steps to your lesson",
    "railCounterClarifying": "2 steps to your lesson",
    "railCounterProbing": "1 step to your lesson",
    "railCounterPlanning": "Approve to build your lesson",
    "railCounterGenerating": "Your lesson is on the way",
    "railProbePosition": "Question {n} of {total}",
    "onTheWaySubline": "You can safely close this window — your lesson will be ready when you get back.",
    "backToSessions": "Back to my sessions"
  },
  "session": {
    "notFound": {
      "title": "Session not found",
      "note": "That session doesn't exist — it may have been removed."
    },
    "error": {
      "title": "Something went wrong",
      "note": "This session hit an error. Head back and try again."
    },
    "notReady": {
      "title": "Materials aren't ready yet",
      "note": "They're generated in the background once your plan is approved."
    },
    "generating": {
      "title": "Generating materials…",
      "note": "Hang tight — your slides and questions are being prepared.",
      "pollingNote": "We can't reach the backend right now — we'll keep trying."
    },
    "learningSession": "Learning session",
    "backToSessions": "Back to my sessions",
    "slide": "Slide",
    "quiz": "Quiz",
    "correct": "Correct.",
    "notQuite": "Not quite.",
    "slideOf": "Slide {n} of {total}",
    "prevSlide": "Previous slide",
    "nextSlide": "Next slide",
    "loading": {
      "title": "Loading session…",
      "note": "Hang tight — your session is loading."
    }
  },
  "phases": {
    "ready": {
      "label": "Ready",
      "hint": "Describe what you want to learn"
    },
    "clarifying": {
      "label": "Clarifying",
      "hint": "Pinning down your goal"
    },
    "probing": {
      "label": "Probing",
      "hint": "Testing your understanding"
    },
    "planning": {
      "label": "Planning",
      "hint": "Building your study plan"
    },
    "reviewing": {
      "label": "Reviewing",
      "hint": "Adjusting the plan"
    },
    "generating": {
      "label": "Generating",
      "hint": "Preparing the steps"
    },
    "executing": {
      "label": "Executing",
      "hint": "Working through the steps"
    },
    "complete": {
      "label": "Complete",
      "hint": "Session finished"
    },
    "error": {
      "label": "Error",
      "hint": "Something went wrong"
    }
  },
  "auth": {
    "tabSignIn": "Sign in",
    "tabCreateAccount": "Create account",
    "email": "Email",
    "password": "Password",
    "displayName": "Display name",
    "displayNamePlaceholder": "Your name (optional)",
    "passwordTooShort": "Password must be at least 8 characters.",
    "invalidCredentials": "Invalid email or password.",
    "emailAlreadyInUse": "Email already in use.",
    "genericError": "Something went wrong. Please try again.",
    "submitSignIn": "Sign in",
    "submitCreateAccount": "Create account",
    "submitting": "Submitting…"
  },
  "time": {
    "justNow": "just now",
    "minAgo": "{n, plural, one {# min ago} other {# min ago}}",
    "yesterday": "Yesterday",
    "hrsAgo": "{n, plural, one {# hr ago} other {# hrs ago}}"
  },
  "review": {
    "title": "Review",
    "progress": "{current} / {total}",
    "emptyTitle": "All clear",
    "emptyBody": "No cards are due right now — keep studying!",
    "loading": "Loading your review deck…",
    "error": {
      "title": "Can't load your review deck",
      "note": "We couldn't reach the backend."
    },
    "retry": "Retry",
    "answerFailed": "Couldn't record your answer — tap a confidence to try again.",
    "backToSessions": "Back to my sessions",
    "reveal": "Reveal answer",
    "confidence": "How confident were you?",
    "again": "Again",
    "hard": "Hard",
    "good": "Good",
    "easy": "Easy",
    "confirm": "Confirm"
  }
};
export default messages;